init:
  - git config --global core.autocrlf input
build_script:
  - cmd: build.cmd -t AppVeyor
test: off
version: 1.0.0.{build}
artifacts:
  - path: bin
    name: bin
  - path: bin/*.nupkg
    name: nuget
nuget:
  project_feed: true

